import { Inter, Roboto } from "next/font/google";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
import "./globals.css";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
